USE [master]
GO

/****** Object:  Database [escuelaDB]    Script Date: 30/9/2020 00:34:46 ******/
CREATE DATABASE [escuelaDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'escuelaDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\escuelaDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'escuelaDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\escuelaDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [escuelaDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [escuelaDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [escuelaDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [escuelaDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [escuelaDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [escuelaDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [escuelaDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [escuelaDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [escuelaDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [escuelaDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [escuelaDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [escuelaDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [escuelaDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [escuelaDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [escuelaDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [escuelaDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [escuelaDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [escuelaDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [escuelaDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [escuelaDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [escuelaDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [escuelaDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [escuelaDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [escuelaDB] SET RECOVERY FULL 
GO

ALTER DATABASE [escuelaDB] SET  MULTI_USER 
GO

ALTER DATABASE [escuelaDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [escuelaDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [escuelaDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [escuelaDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [escuelaDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [escuelaDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [escuelaDB] SET  READ_WRITE 
GO

