//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace esscuelaAdmBackend.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class escuelaDBEntities : DbContext
    {
        public escuelaDBEntities()
            : base("name=escuelaDBEntities")

        {
            Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<escuela> escuela { get; set; }
        public DbSet<estudiante> estudiante { get; set; }
        public DbSet<materia> materia { get; set; }
        public DbSet<profesor> profesor { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<trabajo> trabajo { get; set; }
    }
}
