//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace esscuelaAdmBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class escuela
    {
        public escuela()
        {
            this.estudiante = new HashSet<estudiante>();
            this.profesor = new HashSet<profesor>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public string dpto { get; set; }
        public string direccion { get; set; }
        public string tipo { get; set; }
    
        public virtual ICollection<estudiante> estudiante { get; set; }
        public virtual ICollection<profesor> profesor { get; set; }
    }
}
