//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace esscuelaAdmBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class materia
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public string logo { get; set; }
        public Nullable<int> idProfesor { get; set; }
    
        public virtual profesor profesor { get; set; }
    }
}
